### ISSUE TITLE
Please add support for latest th-orphans and syb

### ISSUE THREAD

**Issue by peti** [bmillwood/haskell-src-meta#43] opened 2015-05-16 12:48 UTC
http://packdeps.haskellers.com/feed?needle=haskell-src-meta

Currently, the build fails like so:

~~~~~~~~~~~
src/Language/Haskell/Meta/Utils.hs:67:1:
    Duplicate instance declarations:
      instance Typeable Q
        -- Defined at src/Language/Haskell/Meta/Utils.hs:67:1
      instance Typeable Q -- Defined in ‘Language.Haskell.TH.Instances’

src/Language/Haskell/Meta/Utils.hs:71:1:
    Duplicate instance declarations:
      instance Typeable QuasiQuoter
        -- Defined at src/Language/Haskell/Meta/Utils.hs:71:1
      instance Typeable QuasiQuoter
        -- Defined in ‘Language.Haskell.TH.Instances’
~~~~~~~~~~~~~

**Comment by bmillwood** [comment] 2015-05-31 12:51
Can't reproduce this. What versions are you using?

**Comment by peti** [comment] 2015-05-31 18:06
It's probably not so important to try and re-produce exactly the error I ran into while running a patched build. What matters is that there is an official release version of `haskell-src-meta` that accepts current versions of `th-orphans` and `syb`.

**Comment by ddssff** [comment] 2015-05-31 23:02
The Typeable instances appeared in th-orphans-0.12.0

**Comment by peti** [comment] 2015-06-18 12:50
Ping?

**Comment by snoyberg** [comment] 2015-06-23 09:32
This is also a problem for Stackage: https://github.com/fpco/stackage/issues/591

**Comment by mainland** [comment] 2015-06-24 12:38
Fixed in version 0.6.0.10.

**Closed by mainland** 2015-06-24 12:38 UTC
